env:
  es6: true
  node: true
  "browser": true
  jest/globals: true
extends: ['eslint:recommended', 'plugin:jest/recommended', "plugin:react/recommended"]
plugins: ['jest', 'react']
parserOptions:
  ecmaVersion: 2018
  ecmaFeatures:
    jsx: true
  sourceType: module
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - off
  comma-dangle:
    - error
    - only-multiline
  react/prop-types:
    - 0