version: '3'

services:
  db:
    image: postgres:10.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    command: yarn build:prod
    volumes:
      - .:/code
    depends_on:
      - db

  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    command: pipenv shell
    command: python manage.py migrate
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - client

volumes:
  postgres_data: