version: '3'

services:
  db:
    image: postgres:10.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"

  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    command: pipenv shell
    command: python manage.py migrate    
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=taskboard.settings_dev
    volumes:
      - .:/code
    ports:
      - "1337:8000"
    depends_on:
      - db

  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    command: yarn dev --port 1338
    ports:
      - "1338:1338"
      - "49153:49153"
    volumes:
      - .:/code
    depends_on:
      - server

volumes:
  postgres_data: